### ISSUE TITLE
使用wss 无法连接问题。就是使用wss://127.0.0.1:8086/socketServer/"+$("#username").val()) 

### ISSUE THREAD

**Issue by dukang-666** [niezhiliang/springbootwebsocket#2]
项目安装了ssl 证书。连接方式改为wss 。客户端无法连接服务端

**Comment by niezhiliang** [comment]
部署证书以后就需要用域名来访问啦  eg: wss://test.test.cn:3838/admin/convert/1571190291000359422 
如果是使用nginx部署的证书  而项目本身没有不是证书的话 则需要在nginx里面配置
具体配置请参考我之前写的一篇博客：https://blog.csdn.net/qq_38082304/article/details/85197636

**Comment by dukang-666** [comment]
谢谢啦 




------------------ 原始邮件 ------------------
发件人: "苏雨丶"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 上午9:48
收件人: "niezhiliang/springbootwebsocket"<springbootwebsocket@noreply.github.com>; 
抄送: ""<1341450685@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [niezhiliang/springbootwebsocket] 使用wss 无法连接问题。就是使用wss://127.0.0.1:8086/socketServer/"+$("#username").val())  (#2)




部署证书以后就需要用域名来访问啦  eg: wss://test.test.cn:3838/admin/convert/1571190291000359422
 如果是使用nginx部署的证书  而项目本身没有不是证书的话 则需要在nginx里面配置
 具体配置请参考我之前写的一篇博客：https://blog.csdn.net/qq_38082304/article/details/85197636
